# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ManyToManyField(related_name='_user_friend_+', to='wall.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_messages', to='wall.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_messages', to='wall.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='wall.User'),
        ),
    ]
